// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { BylineSummary, ContentBylineCredit, TaxonomyTerm, PortableTextBlock } from "emdash";

export interface Design {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  summary?: string;
  content?: PortableTextBlock[];
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  gallery?: unknown;
  client?: string;
  medium?: string;
  year?: string;
  live_url?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Dev {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  summary?: string;
  content?: PortableTextBlock[];
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  repo_url?: string;
  live_url?: string;
  stack?: string;
  language?: string;
  year?: string;
  project_status?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Policy {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  summary?: string;
  content?: PortableTextBlock[];
  publication?: string;
  date?: string;
  topic?: string;
  link?: string;
  pdf_url?: string;
  coauthors?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Writing {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  summary?: string;
  content?: PortableTextBlock[];
  publication?: string;
  date?: string;
  topic?: string;
  link?: string;
  excerpt?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

declare module "emdash" {
  interface EmDashCollections {
    design: Design;
    dev: Dev;
    pages: Page;
    policy: Policy;
    writing: Writing;
  }
}