-- Preserve orphaned metadata from earlier seeds, then remove only those orphan rows.
-- Public content and revisions are not changed.
CREATE TABLE IF NOT EXISTS _portfolio_legacy_metadata (source_table TEXT NOT NULL, source_id TEXT NOT NULL, data TEXT NOT NULL, archived_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (source_table,source_id));
INSERT OR IGNORE INTO _portfolio_legacy_metadata (source_table,source_id,data) SELECT '_emdash_fields',id,json_object('id',id,'collection_id',collection_id,'slug',slug,'label',label,'type',type,'column_type',column_type,'required',required,'unique',"unique",'default_value',default_value,'validation',validation,'widget',widget,'options',options,'sort_order',sort_order,'created_at',created_at,'searchable',searchable,'translatable',translatable) FROM _emdash_fields WHERE id IN ('01KN5VX628558J9QPN3YDX6H79','01KN5VX6294VHMQNH57REBW7XP','01KN5VX62AE5VVZ8R058BPZTAK','01KN5VX62BEJX3F8E9WTQKC17T','01KN5VX62BG281PKS1P6XEWE4E','01KN5VX62C4WQR9XD6QNR979Q9','01KN5VX62D9KTH63A9PRB4TE47','01KN5VX62ERMTC5240E6MKEGA9','01KN5VX62FF2H4T1WSA9TJVFJY','01KN5VX62FDMR57TE872H933N4') AND collection_id NOT IN (SELECT id FROM _emdash_collections);
DELETE FROM _emdash_fields WHERE id IN ('01KN5VX628558J9QPN3YDX6H79','01KN5VX6294VHMQNH57REBW7XP','01KN5VX62AE5VVZ8R058BPZTAK','01KN5VX62BEJX3F8E9WTQKC17T','01KN5VX62BG281PKS1P6XEWE4E','01KN5VX62C4WQR9XD6QNR979Q9','01KN5VX62D9KTH63A9PRB4TE47','01KN5VX62ERMTC5240E6MKEGA9','01KN5VX62FF2H4T1WSA9TJVFJY','01KN5VX62FDMR57TE872H933N4') AND collection_id NOT IN (SELECT id FROM _emdash_collections) AND EXISTS (SELECT 1 FROM _portfolio_legacy_metadata a WHERE a.source_table='_emdash_fields' AND a.source_id=_emdash_fields.id AND a.data=json_object('id',id,'collection_id',collection_id,'slug',slug,'label',label,'type',type,'column_type',column_type,'required',required,'unique',"unique",'default_value',default_value,'validation',validation,'widget',widget,'options',options,'sort_order',sort_order,'created_at',created_at,'searchable',searchable,'translatable',translatable));
INSERT OR IGNORE INTO _portfolio_legacy_metadata (source_table,source_id,data) SELECT '_emdash_menu_items',id,json_object('id',id,'menu_id',menu_id,'parent_id',parent_id,'sort_order',sort_order,'type',type,'reference_collection',reference_collection,'reference_id',reference_id,'custom_url',custom_url,'label',label,'title_attr',title_attr,'target',target,'css_classes',css_classes,'created_at',created_at) FROM _emdash_menu_items WHERE id IN ('01KN5Z8S39FAF94B5477XCZ5NC','01KN5Z8S5FYYH4ETM7RXXYQS0X','01KN5Z8S7NG1MGV0TV70V1Z7Z8','01KN5VX62MYMDJY3GJ02H2BRFZ','01KN5VX62MPNVKHAHZ655X28B7') AND menu_id NOT IN (SELECT id FROM _emdash_menus);
DELETE FROM _emdash_menu_items WHERE id IN ('01KN5Z8S39FAF94B5477XCZ5NC','01KN5Z8S5FYYH4ETM7RXXYQS0X','01KN5Z8S7NG1MGV0TV70V1Z7Z8','01KN5VX62MYMDJY3GJ02H2BRFZ','01KN5VX62MPNVKHAHZ655X28B7') AND menu_id NOT IN (SELECT id FROM _emdash_menus) AND EXISTS (SELECT 1 FROM _portfolio_legacy_metadata a WHERE a.source_table='_emdash_menu_items' AND a.source_id=_emdash_menu_items.id AND a.data=json_object('id',id,'menu_id',menu_id,'parent_id',parent_id,'sort_order',sort_order,'type',type,'reference_collection',reference_collection,'reference_id',reference_id,'custom_url',custom_url,'label',label,'title_attr',title_attr,'target',target,'css_classes',css_classes,'created_at',created_at));
DROP TRIGGER IF EXISTS _emdash_fts_design_update;
CREATE TRIGGER _emdash_fts_design_update AFTER UPDATE ON ec_design BEGIN
  INSERT INTO _emdash_fts_design(_emdash_fts_design, rowid, id, locale, title, summary, content) VALUES ('delete', OLD.rowid, OLD.id, OLD.locale, OLD.title, OLD.summary, OLD.content);
  INSERT INTO _emdash_fts_design(rowid, id, locale, title, summary, content) VALUES (NEW.rowid, NEW.id, NEW.locale, NEW.title, NEW.summary, NEW.content);
END;
DROP TRIGGER IF EXISTS _emdash_fts_design_delete;
CREATE TRIGGER _emdash_fts_design_delete AFTER DELETE ON ec_design BEGIN
  INSERT INTO _emdash_fts_design(_emdash_fts_design, rowid, id, locale, title, summary, content) VALUES ('delete', OLD.rowid, OLD.id, OLD.locale, OLD.title, OLD.summary, OLD.content);
END;
INSERT INTO _emdash_fts_design(_emdash_fts_design) VALUES ('rebuild');
INSERT INTO _emdash_fts_design(_emdash_fts_design, rank) VALUES ('integrity-check', 1);
