/**
 * HeroBlocks — an order-able block-based hero template.
 *
 * Unlike the other hero templates which lock their render order, this
 * template accepts an array of typed blocks and renders them in the
 * order given. Editors can drag, reorder, insert, and delete blocks
 * freely from the admin UI.
 *
 * Supported block types:
 *   - headline    h1 with the page's primary headline
 *   - subhead     lead paragraph under the headline
 *   - body        multi-paragraph body copy (splits on double-newlines)
 *   - image       full-width image with optional alt + credit
 *   - pull_quote  italicized blockquote with left accent border
 *   - divider     horizontal rule
 *   - spacer      blank vertical gap (height in rem)
 *   - rich_text   raw HTML (sanitized upstream — trusted admin input only)
 *
 * Unknown block types are silently skipped so forward-compatible configs
 * never fail to render.
 */

import type { CSSProperties, ReactNode } from "react";

export type HeroBlockType =
  | "headline"
  | "subhead"
  | "body"
  | "image"
  | "pull_quote"
  | "divider"
  | "spacer"
  | "rich_text";

export interface HeroBlockBase {
  /** Stable id for React keys + reorder. Generated by the admin UI. */
  id: string;
  type: HeroBlockType;
}

export interface HeadlineBlock extends HeroBlockBase {
  type: "headline";
  text: string;
}
export interface SubheadBlock extends HeroBlockBase {
  type: "subhead";
  text: string;
}
export interface BodyBlock extends HeroBlockBase {
  type: "body";
  text: string;
}
export interface ImageBlock extends HeroBlockBase {
  type: "image";
  url: string;
  alt?: string;
  credit?: string;
}
export interface PullQuoteBlock extends HeroBlockBase {
  type: "pull_quote";
  text: string;
  attribution?: string;
}
export interface DividerBlock extends HeroBlockBase {
  type: "divider";
}
export interface SpacerBlock extends HeroBlockBase {
  type: "spacer";
  /** Height in rem. Clamped to 0-8 at render time. */
  height?: number;
}
export interface RichTextBlock extends HeroBlockBase {
  type: "rich_text";
  html: string;
}

export type HeroBlock =
  | HeadlineBlock
  | SubheadBlock
  | BodyBlock
  | ImageBlock
  | PullQuoteBlock
  | DividerBlock
  | SpacerBlock
  | RichTextBlock;

export interface HeroBlocksProps {
  blocks: HeroBlock[];
}

const wrapperStyle: CSSProperties = {
  padding: "2.5rem 1.5rem 2rem",
  maxWidth: "40em",
  margin: "0 auto",
};

const headlineStyle: CSSProperties = {
  fontFamily: "var(--page-font-serif, Georgia, serif)",
  color: "var(--page-text, #1a1a1a)",
  fontSize: "clamp(2rem, 5vw, 3.25rem)",
  fontWeight: 700,
  lineHeight: 1.15,
  letterSpacing: "-0.015em",
  margin: 0,
};

const subheadStyle: CSSProperties = {
  fontFamily: "var(--page-font-serif, Georgia, serif)",
  color: "var(--page-secondary, #555)",
  fontSize: "clamp(1.05rem, 2.5vw, 1.3rem)",
  lineHeight: 1.5,
  margin: 0,
};

const bodyWrapStyle: CSSProperties = {
  color: "var(--page-secondary, #555)",
  fontSize: "1.075rem",
  lineHeight: 1.7,
};

const pullQuoteStyle: CSSProperties = {
  fontFamily: "var(--page-font-serif, Georgia, serif)",
  color: "var(--page-text, #1a1a1a)",
  fontSize: "clamp(1.2rem, 3vw, 1.5rem)",
  fontStyle: "italic",
  fontWeight: 400,
  lineHeight: 1.5,
  margin: 0,
  padding: "0.25rem 0 0.25rem 1.25rem",
  borderLeft: "3px solid var(--page-accent, #c00)",
};

const figureStyle: CSSProperties = {
  margin: 0,
};

const imageStyle: CSSProperties = {
  width: "100%",
  height: "auto",
  maxHeight: "520px",
  objectFit: "cover",
  borderRadius: "var(--page-radius, 4px)",
  display: "block",
};

const imageCreditStyle: CSSProperties = {
  fontFamily: "var(--page-font-mono, monospace)",
  fontSize: "0.7rem",
  color: "var(--page-secondary, #777)",
  marginTop: "0.5rem",
  textAlign: "right",
  letterSpacing: "0.03em",
};

const dividerStyle: CSSProperties = {
  border: "none",
  borderTop: "1px solid var(--page-border, #d4d4c8)",
  margin: 0,
};

const quoteAttrStyle: CSSProperties = {
  fontFamily: "var(--page-font-mono, monospace)",
  fontSize: "0.75rem",
  color: "var(--page-secondary, #777)",
  marginTop: "0.75rem",
  textTransform: "uppercase",
  letterSpacing: "0.08em",
};

/** Default vertical gap between blocks, in rem. Applied to block 2 onward. */
const BLOCK_GAP_REM = 1.5;

function renderBlock(block: HeroBlock): ReactNode {
  switch (block.type) {
    case "headline":
      return <h1 style={headlineStyle}>{block.text}</h1>;
    case "subhead":
      return <p style={subheadStyle}>{block.text}</p>;
    case "body": {
      const paragraphs = (block.text ?? "").split(/\n{2,}/);
      return (
        <div style={bodyWrapStyle}>
          {paragraphs.map((p, i) => (
            <p key={i} style={{ margin: 0, marginTop: i > 0 ? "1.2em" : 0 }}>
              {p}
            </p>
          ))}
        </div>
      );
    }
    case "image":
      if (!block.url) return null;
      return (
        <figure style={figureStyle}>
          <img
            src={block.url}
            alt={block.alt ?? ""}
            loading="lazy"
            style={imageStyle}
          />
          {block.credit && <figcaption style={imageCreditStyle}>{block.credit}</figcaption>}
        </figure>
      );
    case "pull_quote":
      return (
        <blockquote style={pullQuoteStyle}>
          {block.text}
          {block.attribution && <div style={quoteAttrStyle}>— {block.attribution}</div>}
        </blockquote>
      );
    case "divider":
      return <hr style={dividerStyle} />;
    case "spacer": {
      const h = Math.max(0, Math.min(8, block.height ?? 1));
      return <div style={{ height: `${h}rem` }} aria-hidden />;
    }
    case "rich_text":
      // Admin-trusted content — editors set this via PageBuilder and
      // the site's action renderer does not re-sanitize. If the admin
      // UI accepts untrusted input in the future, this MUST pass through
      // a sanitizer before rendering.
      return <div dangerouslySetInnerHTML={{ __html: block.html }} />;
    default:
      // Forward-compat: unknown types are silently skipped.
      return null;
  }
}

export function HeroBlocks({ blocks }: HeroBlocksProps): ReactNode {
  if (!Array.isArray(blocks) || blocks.length === 0) return null;
  return (
    <article style={wrapperStyle}>
      {blocks.map((block, i) => {
        const marginTop = i === 0 ? 0 : `${BLOCK_GAP_REM}rem`;
        const content = renderBlock(block);
        if (content == null) return null;
        return (
          <div key={block.id || `b${i}`} style={{ marginTop }}>
            {content}
          </div>
        );
      })}
    </article>
  );
}

/**
 * Validate a blocks payload. Returns a cleaned copy with invalid blocks
 * removed and missing ids backfilled. Never throws.
 *
 * Rules:
 *   - blocks must be an array (otherwise returns [])
 *   - each block must have a known type
 *   - headline/subhead/body/rich_text require a non-empty string
 *   - pull_quote requires text
 *   - image requires url
 *   - spacer accepts optional numeric height, default 1
 *   - divider has no required fields
 *   - MAX 64 blocks per page (hard cap to bound render cost)
 */
export const MAX_HERO_BLOCKS = 64;

export function validateHeroBlocks(raw: unknown): HeroBlock[] {
  if (!Array.isArray(raw)) return [];
  const out: HeroBlock[] = [];
  for (const [i, item] of raw.entries()) {
    if (out.length >= MAX_HERO_BLOCKS) break;
    if (!item || typeof item !== "object") continue;
    const b = item as Record<string, unknown>;
    const type = b.type as HeroBlockType;
    const id = typeof b.id === "string" && b.id.length > 0 ? b.id : `b${i}`;

    switch (type) {
      case "headline":
      case "subhead":
      case "body": {
        const text = typeof b.text === "string" ? b.text : "";
        if (!text.trim()) continue;
        out.push({ id, type, text } as HeroBlock);
        break;
      }
      case "image": {
        const url = typeof b.url === "string" ? b.url : "";
        if (!url.trim()) continue;
        out.push({
          id,
          type: "image",
          url,
          alt: typeof b.alt === "string" ? b.alt : undefined,
          credit: typeof b.credit === "string" ? b.credit : undefined,
        });
        break;
      }
      case "pull_quote": {
        const text = typeof b.text === "string" ? b.text : "";
        if (!text.trim()) continue;
        out.push({
          id,
          type: "pull_quote",
          text,
          attribution: typeof b.attribution === "string" ? b.attribution : undefined,
        });
        break;
      }
      case "divider":
        out.push({ id, type: "divider" });
        break;
      case "spacer": {
        const height =
          typeof b.height === "number" && Number.isFinite(b.height)
            ? b.height
            : 1;
        out.push({ id, type: "spacer", height });
        break;
      }
      case "rich_text": {
        const html = typeof b.html === "string" ? b.html : "";
        if (!html.trim()) continue;
        out.push({ id, type: "rich_text", html });
        break;
      }
      default:
        // Unknown type — drop.
        continue;
    }
  }
  return out;
}
